version: '3'
services:
  ray_head:
    build : ./head/
    container_name: ray_head
    shm_size: '12gb'
    expose:
      - "6379:6379"
      - "8265:8265"
      - "10001:10001"
      - "8000:8000"
    ports:
      - "8000:8000"
      - "8265:8265"

  ray_worker:
    build : ./worker/
    container_name: ray_worker
    depends_on:
      - ray_head
    environment:
      - RAY_HEAD_ADDRESS=ray_head:6379
    shm_size: '12gb'

  ray_client:
    build : ./client/
    container_name: ray_client
    depends_on:
      - ray_head
    environment:
      - RAY_HOST=ray_head
      - RAY_HEAD_ADDRESS=ray_head:6379
      - RAY_HEAD_CLIENT_CONNECT_ADDRESS=ray_head:10001
      - RAY_HEAD_DASHBOARD_ADDRESS=ray_head:8265
